

---
apiVersion: v1
kind: Pod
metadata:
  name: facebook
  labels:
    app: facebook
spec:
  containers:
  - name: facebook
    image: nginx:latest
    ports:
    - containerPort: 80

    resources:
      requests:
        memory: "64Mi"  # need minimum 64Mi memory and 250m cpu to run the container
        cpu: "250m"
     
      limits:
        memory: "512Mi"  # can use maximum 512Mi memory and 500m cpu to run the container
        cpu: "500m"